# ---------------------------------------------------------------------------------------
#   @parent     : github workflow
#   @desc       : checks for certain phrases in an issue title and body
#   @author     : Aetherinox
#   @url        : https://github.com/Aetherinox
# ---------------------------------------------------------------------------------------

name: "New Issue: OpenGist Check"
run-name: "New Issue: OpenGist Check - ${{ github.event.issue.number }}: ${{ github.event.issue.title }}"

on:
  issues:
    types: [opened]

env:
  ACTION_NAME: OpenGist
  ASSIGN_USER: Aetherinox
  BOT_NAME_1: AdminServ
  BOT_NAME_2: AdminServX

jobs:

  # ---------------------------------------------------------------------------------------
  # Check for phrase [ OpenGist ]
  # ---------------------------------------------------------------------------------------

  Phrase_OpenGist_Check:
    name:  "Phrase Check [ OpenGist ]"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

      # Check Submission TITLE to phrase "OpenGist"

      - name: ${{ env.ACTION_NAME }} [ Title ] - String Manipulation
        id: og_title
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.event.issue.title }}

      - name: ${{ env.ACTION_NAME }} [ Title ] - Check Phrase
        if: |
          github.event.issue &&
          github.event.issue.user.login != '$env.BOT_NAME_1' &&
          github.event.issue.user.login != '$env.BOT_NAME_2' &&
          ( contains( steps.og_title.outputs.lowercase, 'opengist' ) ||
          contains( steps.og_title.outputs.lowercase, 'open gist' ) )
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.ADMINSERV_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ⚠️ It appears you may be looking for OpenGist help.
            - [Opengist Repo](https://github.com/thomiceli/opengist)
            - [Opengist Docs](https://github.com/thomiceli/opengist/blob/master/docs/index.md)
            - [Opengist Demo](https://opengist.thomice.li/all)

            If you are looking for OpenGist support, it will be very minimal. Please utilize the links above.

            ---

            <sub>I am a bot reaching out to you with an automated response. If the above info doesn't apply to you, please ignore it.</sub>

      # Check Submission BODY to phrase "OpenGist"

      - name: ${{ env.ACTION_NAME }} [ Body ] - String Manipulation
        id: og_body
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.event.issue.body }}

      - name: ${{ env.ACTION_NAME }} [ Body ] - Check Phrase
        if: |
          github.event.issue &&
          github.event.issue.user.login != '$env.BOT_NAME_1' &&
          github.event.issue.user.login != '$env.BOT_NAME_2' &&
          ( contains( steps.og_body.outputs.lowercase, 'opengist' ) ||
          contains( steps.og_body.outputs.lowercase, 'open gist' ) )
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.ADMINSERV_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ⚠️ It appears you may be looking for OpenGist help.
            - [Opengist Repo](https://github.com/thomiceli/opengist)
            - [Opengist Docs](https://github.com/thomiceli/opengist/blob/master/docs/index.md)
            - [Opengist Demo](https://opengist.thomice.li/all)

            If you are looking for OpenGist support, it will be very minimal. Please utilize the links above.

            ---

            <sub>I am a bot reaching out to you with an automated response. If the above info doesn't apply to you, please ignore it.</sub>