name: "Issues: Keyword OpenGist"

on:
  issues:
    types: [opened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    if: |
      github.event.issue &&
      github.event.issue.user.login != 'AdminServX' &&
      github.event.issue.user.login != 'AdminServ' &&
      ( contains( github.event.issue.body, 'opengist' ) ||
      contains( github.event.issue.body, 'OpenGist' ) ||
      contains( github.event.issue.body, 'Opengist' ) ||
      contains( github.event.issue.body, 'openGist' ) )

    steps:
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: "bug"
      - run: gh issue edit "$NUMBER" --add-assignee "$ASSIGNEE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          ASSIGNEE: Aetherinox
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.ADMINSERV_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ⚠️ It appears you may be looking for OpenGist help.
            - [Opengist Repo](https://github.com/thomiceli/opengist)
            - [Opengist Docs](https://github.com/thomiceli/opengist/blob/master/docs/index.md)
            - [Opengist Demo](https://opengist.thomice.li/all)

            If you are looking for OpenGist support, it will be very minimal. Please utilize the links above.

            ---

            <sub>I am a bot reaching out to you with an automated response. If the above info doesn't apply to you, please ignore it.</sub>